export const SAVE_SEARCH_BOOK_VALUE = "SAVE_SEARCH_BOOK_VALUE"
export const SAVE_SEARCH_BOOK_LIST = "SAVE_SEARCH_BOOK_LIST"
export const CLEAR_SEARCH_VALUE= "CLEAR_SEARCH_VALUE"
export const CLEAR_SEARCH_LIST = "CLEAR_SEARCH_LIST"